services:
  wqp-frost:
    container_name: wqp-frost
    build:
      context: ./modules/frost
      dockerfile: Dockerfile
    # platform: linux/amd64
    environment:
      - serviceRootUrl=${WQP_URL}/FROST-Server
      - persistence_db_url=jdbc:postgresql://wqp-database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - FROST_LL=DEBUG
    depends_on:
      - wqp-database
    ports:
      - 8080:8080

  wqp-database:
    container_name: wqp-database
    build:
      context: ./modules/database
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data

  wqp-pygeoapi:
    container_name: wqp-pygeoapi
    build:
      context: modules/pygeoapi
    depends_on:
      - wqp-frost
    environment:
      - API_URL=${WQP_URL}/oapi
      - API_BACKEND_URL=http://wqp-frost:8080/FROST-Server/v1.1
      - SCRIPT_NAME=/oapi

  wqp-proxy:
    container_name: wqp-proxy
    build:
      context: modules/nginx
    restart: always
    ports:
      - 8888:80

  wqp-dagster:
    container_name: wqp-dagster
    build:
      context: .
    command: ["US:08:004"]
    environment:
      - API_BACKEND_URL=http://wqp-frost:8080/FROST-Server/v1.1
      - SLACK_BOT_TOKEN
    deploy:
      resources:
        limits:
          cpus: "7"
          memory: 4GB

volumes:
  postgis_volume:
